name: quranallriwayat
description: A new Flutter project.

publish_to: none
version: 1.0.0+2

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  adwaita: ^1.0.0
  archive: ^3.3.7
  desktop_multi_window: ^0.2.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  flutter_localization: ^0.1.11
  libadwaita: ^2.0.1
  libadwaita_window_manager: ^0.5.4+1
  window_manager:
  path: ^1.8.3
  path_provider: ^2.0.15
  get: ^4.6.1
  sqflite_common_ffi: ^2.2.5
  sqlite3_flutter_libs:
  http: ^0.13.6
  shared_preferences: ^2.0.15
  fast_cached_network_image: ^1.2.0
  toast: ^0.2.9
  firebase_storage: ^11.2.3
  hive_local_storage: ^1.0.6
  sqlite3: ^2.0.0
  collection: ^1.17.1
  url_launcher: ^6.1.12
  syncfusion_localizations: ^22.1.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  #very_good_analysis: ^3.0.1
  flutter_lints: ^2.0.0

# dependency_overrides:
#   file:
#     git:
#       url: https://github.com/google/file.dart
#       ref: release
#       path: packages/file

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/images/
    - assets/quranTypeImages/