// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5N8FcwnIwGAhMSE1zleUaM6i1ooz41uM',
    appId: '1:1053268239975:web:b47e4a608945bc5bcbd6c2',
    messagingSenderId: '1053268239975',
    projectId: 'recitemaan',
    authDomain: 'recitemaan.firebaseapp.com',
    storageBucket: 'recitemaan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr-y89-lYyBANvJGQOPxbl6yGd-mipe_o',
    appId: '1:1053268239975:android:b7ccec66d8ac074ecbd6c2',
    messagingSenderId: '1053268239975',
    projectId: 'recitemaan',
    storageBucket: 'recitemaan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3y8jpG9bBmo4xoOfULMBzDCYJPysuwmU',
    appId: '1:1053268239975:ios:255de022033aa101cbd6c2',
    messagingSenderId: '1053268239975',
    projectId: 'recitemaan',
    storageBucket: 'recitemaan.appspot.com',
    androidClientId: '1053268239975-n4heej5qvrsmbgts6pv5qmu8u9hroauu.apps.googleusercontent.com',
    iosClientId: '1053268239975-jtlp2inq471bi7e7j0hmrpunb200s4tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.quraan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3y8jpG9bBmo4xoOfULMBzDCYJPysuwmU',
    appId: '1:1053268239975:ios:255de022033aa101cbd6c2',
    messagingSenderId: '1053268239975',
    projectId: 'recitemaan',
    storageBucket: 'recitemaan.appspot.com',
    androidClientId: '1053268239975-n4heej5qvrsmbgts6pv5qmu8u9hroauu.apps.googleusercontent.com',
    iosClientId: '1053268239975-jtlp2inq471bi7e7j0hmrpunb200s4tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.quraan',
  );
}
