import 'package:flutter/material.dart';
import 'theme_model.dart';

final ThemeModel defaultLight = ThemeModel(
  theme: 'defaultLight',
  primary: const Color(0xFF0E1EA0),
  onPrimary: const Color(0xFFDADCE7),
  secondary: const Color(0xFF81d3f9),
  onSecondary: const Color(0xFF0E1EA0),
  surface: const Color(0xff09205e),
  onSurface: const Color(0xFFDADCE7),
  background: const Color(0xFF000534),
  onBackground: const Color(0xFFDADCE7),
  outline: const Color(0xFF0E1EA0),
  layoutStyle: 'styleOne',
  brightness: Brightness.light,
  radius: 10,
  primaryContainer: const Color(0xFFFFDCC3),
  onPrimaryContainer: const Color(0xFF301400),
  secondaryContainer: const Color(0xFFFFDF96),
  onSecondaryContainer: const Color(0xFF261A00),
  errorContainer: const Color(0xFFF9DEDF),
  onErrorContainer: const Color(0xFF410E0B),
  tertiary: const Color(0xFF58c9b0),
  onTertiary: const Color(0xFFFFFFFF),
  onError: const Color(0xFFFFFFFF),
);

final ThemeModel defaultDark = ThemeModel(
  theme: 'defaultDark',
  primary: const Color(0xFF16171b),
  onPrimary: const Color(0xFFFFFFFF),
  primaryContainer: const Color(0xFFFFDCC3),
  onPrimaryContainer: const Color(0xFF301400),
  secondary: const Color(0xFFFFDF9B),
  onSecondary: const Color(0xFF261900),
  secondaryContainer: const Color(0xFFFFDF96),
  onSecondaryContainer: const Color(0xFF261A00),
  tertiary: const Color(0xFF58c9b0),
  onTertiary: const Color(0xFFFFFFFF),
  //tertiaryContainer: Color(0xFFFFffff),
  //onTertiaryContainer: Color(0xFF31111D),
  error: const Color(0xFFB3261E),
  onError: const Color(0xFFFFFFFF),
  errorContainer: const Color(0xFFF9DEDF),
  onErrorContainer: const Color(0xFF410E0B),
  background: const Color(0xFFFFFBF4),
  onBackground: const Color(0xFF1C1B1F),
  surface: const Color(0xFFffffff), //Color(0xFFfffbf0),
  onSurface: const Color(0xFF1C1B1F),
  //surfaceVariant: Color(0xFFE7E0EC),
  //onSurfaceVariant: Color(0xFF49454F),
  outline: const Color(0xFF79747E),
  //onInverseSurface: Color(0xFFF4EFF4),
  //inverseSurface: Color(0xFF313033),
  //inversePrimary: Color(0xFFFFB77F),
  //shadow: Color(0xFF000000),
  layoutStyle: 'styleTwo',
  brightness: Brightness.dark,
  radius: 10,
);
